### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "displayName": "Test User",
  "email": "test@premierzone.com",
  "password": "Password123!"
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@premierzone.com",
  "password": "Password123!"
}

### Current user
GET http://localhost:8080/api/v1/auth/me
Authorization: Bearer eyJraWQiOiJQX25yTEkwbzhuY2U1UU9iRVZ0NGJFSFY0X3ctbTFUWUJranFfUTEyUXgwIiwidHlwIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0QHByZW1pZXJ6b25lLmNvbSIsInJvbGUiOiJVU0VSIiwiZGlzcGxheU5hbWUiOiJUZXN0IFVzZXIiLCJpc3MiOiJwcmVtaWVyLXpvbmUiLCJleHAiOjE3ODU1NDUwODQsImlhdCI6MTc4NTU0MTQ4NCwidXNlcklkIjoxfQ.xv6HnE8TVjivFt3eBKbjDhJbAVy-mTsj6ivsEKzYKdo
### Get saved fantasy squad
GET http://localhost:8080/api/v1/fantasy-squad
Authorization: Bearer eyJraWQiOiJQX25yTEkwbzhuY2U1UU9iRVZ0NGJFSFY0X3ctbTFUWUJranFfUTEyUXgwIiwidHlwIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0QHByZW1pZXJ6b25lLmNvbSIsInJvbGUiOiJVU0VSIiwiZGlzcGxheU5hbWUiOiJUZXN0IFVzZXIiLCJpc3MiOiJwcmVtaWVyLXpvbmUiLCJleHAiOjE3ODU1NDUwODQsImlhdCI6MTc4NTU0MTQ4NCwidXNlcklkIjoxfQ.xv6HnE8TVjivFt3eBKbjDhJbAVy-mTsj6ivsEKzYKdo
### Save fantasy squad
PUT http://localhost:8080/api/v1/fantasy-squad
Authorization: Bearer eyJraWQiOiJQX25yTEkwbzhuY2U1UU9iRVZ0NGJFSFY0X3ctbTFUWUJranFfUTEyUXgwIiwidHlwIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0QHByZW1pZXJ6b25lLmNvbSIsInJvbGUiOiJVU0VSIiwiZGlzcGxheU5hbWUiOiJUZXN0IFVzZXIiLCJpc3MiOiJwcmVtaWVyLXpvbmUiLCJleHAiOjE3ODU1MDgxODEsImlhdCI6MTc4NTUwNDU4MSwidXNlcklkIjoxfQ.aLkhJXzJ0it3vO24KSc3fhsqD9XX5PNeioiapvY1Gmw
Content-Type: application/json

[
  {
    "playerName": "Ashley Young",
    "assignedPosition": "DF"
  },
  {
    "playerName": "Antony",
    "assignedPosition": "FW"
  }
]